# Generated by Django 2.1.7 on 2019-03-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corgi_store', '0002_auto_20190328_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corgi',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], default='X', max_length=10),
        ),
    ]
